apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodesy-deployment
  namespace: dev
  labels:
    app: nodesy-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodesy-app
  template:
    metadata:
      labels:
        app: nodesy-app
    spec:
      containers:
        - name: nodesy-container
          image: 765370101522.dkr.ecr.us-east-1.amazonaws.com/nodejs-webapp:latest
          ports:
            - containerPort: 3000